import React, { useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export default function SpecialStructurePanel({ slots, positions, teachers, busy, act }) {
  const [slot, setSlot] = useState({ name: "", start_time: "", end_time: "" }), [position, setPosition] = useState({ name: "", area: "", instructions: "", restriction_type: "all", division: "both", allowed_teacher_ids: [] });
  return <div className="grid gap-3 lg:grid-cols-2"><section className="rounded-xl border bg-card p-4"><h2 className="mb-3 font-bold">מקטעי זמן</h2><div className="space-y-2">{slots.map(s => <div key={s.id} className="flex items-center gap-2 rounded-lg bg-muted/50 p-2 text-sm"><span className="min-w-0 flex-1 font-medium">{s.name}</span><span dir="ltr">{s.start_time}–{s.end_time}</span><button aria-label={`מחיקת ${s.name}`} className="text-destructive" onClick={() => act("delete_slot", { id: s.id })}><Trash2 className="h-4 w-4" /></button></div>)}</div><div className="mt-3 grid grid-cols-3 gap-2"><Input placeholder="שם" value={slot.name} onChange={e => setSlot({ ...slot, name: e.target.value })} /><Input type="time" value={slot.start_time} onChange={e => setSlot({ ...slot, start_time: e.target.value })} /><Input type="time" value={slot.end_time} onChange={e => setSlot({ ...slot, end_time: e.target.value })} /></div><Button className="mt-2 w-full" variant="outline" disabled={busy || !slot.name || !slot.start_time || !slot.end_time} onClick={() => { act("add_slot", { data: { ...slot, sort_order: slots.length } }); setSlot({ name: "", start_time: "", end_time: "" }); }}><Plus />הוספת מקטע</Button></section>
    <section className="rounded-xl border bg-card p-4"><h2 className="mb-3 font-bold">עמדות מיוחדות</h2><div className="space-y-2">{positions.map(p => <div key={p.id} className="flex items-center gap-2 rounded-lg bg-muted/50 p-2 text-sm"><span className="min-w-0 flex-1 font-medium">{p.name}<small className="mr-2 text-muted-foreground">{p.area}</small></span><button aria-label={`מחיקת ${p.name}`} className="text-destructive" onClick={() => act("delete_position", { id: p.id })}><Trash2 className="h-4 w-4" /></button></div>)}</div><div className="mt-3 grid grid-cols-2 gap-2"><Input placeholder="שם עמדה" value={position.name} onChange={e => setPosition({ ...position, name: e.target.value })} /><Input placeholder="אזור" value={position.area} onChange={e => setPosition({ ...position, area: e.target.value })} /></div><textarea className="mt-2 min-h-16 w-full rounded-md border bg-background p-2 text-sm" placeholder="הנחיות לעמדה" value={position.instructions} onChange={e => setPosition({ ...position, instructions: e.target.value })} /><select className="mt-2 h-10 w-full rounded-md border bg-background px-3 text-sm" value={position.restriction_type} onChange={e => setPosition({ ...position, restriction_type: e.target.value })}><option value="all">כל המורים</option><option value="management">מנהלים בלבד</option><option value="sport">מורי ספורט</option><option value="division">חטיבה מסוימת</option><option value="group">קבוצה מוגדרת</option></select>{position.restriction_type === "division" && <select className="mt-2 h-10 w-full rounded-md border bg-background px-3 text-sm" value={position.division} onChange={e => setPosition({ ...position, division: e.target.value })}><option value="middle">חטיבת ביניים</option><option value="high">חטיבה עליונה</option><option value="both">שתי החטיבות</option></select>}{position.restriction_type === "group" && <select multiple aria-label="קבוצת מורים מורשית" className="mt-2 min-h-28 w-full rounded-md border bg-background p-2 text-sm" value={position.allowed_teacher_ids} onChange={e => setPosition({ ...position, allowed_teacher_ids: [...e.target.selectedOptions].map(o => o.value) })}>{teachers.map(t => <option key={t.id} value={t.id}>{t.full_name}</option>)}</select>}<Button className="mt-2 w-full" variant="outline" disabled={busy || !position.name} onClick={() => { act("add_position", { data: { ...position, is_active: true, sort_order: positions.length } }); setPosition({ name: "", area: "", instructions: "", restriction_type: "all", division: "both", allowed_teacher_ids: [] }); }}><Plus />הוספת עמדה</Button></section></div>;
}