import React, { useEffect, useMemo, useState } from "react";
import { Loader2, Send } from "lucide-react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { manageFixedSchedule } from "@/functions/manageFixedSchedule";
import { Button } from "@/components/ui/button";
import { useConfirm } from "@/components/ui/confirm-dialog";
import FixedBreakSection from "@/components/fixed-schedule/FixedBreakSection";
import FixedScheduleToolbar from "@/components/fixed-schedule/FixedScheduleToolbar";
import FixedTeacherSheet from "@/components/fixed-schedule/FixedTeacherSheet";
import FixedPublishDialog from "@/components/fixed-schedule/FixedPublishDialog";
import DraftSummaryBar from "@/components/fixed-schedule/DraftSummaryBar";

const queryKey = ["fixed-schedule"];
export default function FixedSchedule({ embedded = false }) {
  const queryClient = useQueryClient();
  const confirmDialog = useConfirm();
  const { data, isLoading, error } = useQuery({ queryKey, queryFn: () => manageFixedSchedule({ action: "load" }).then(response => response.data), staleTime: 60_000, refetchOnMount: false });
  const requestedDay = Number(new URLSearchParams(window.location.search).get("day"));
  const [day, setDay] = useState(requestedDay >= 0 && requestedDay <= 4 ? requestedDay : 0), [editing, setEditing] = useState(null), [review, setReview] = useState(false), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  const setData = updater => queryClient.setQueryData(queryKey, updater);
  const act = async (action, extra = {}) => { setBusy(true); setMessage(""); try { const response = await manageFixedSchedule({ action, expected_updated_date: data.template.updated_date, ...extra }); setData(response.data); setMessage(action === "auto_assign" ? "טיוטת השבוע נוצרה ונשמרה לבדיקה" : action === "import_assignments" ? "הנתונים יובאו בהצלחה" : action === "publish" ? "הלוח הקבוע פורסם" : "השינויים נשמרו"); return response.data; } catch (failure) { setMessage(failure.response?.data?.error || failure.message); if (failure.response?.data?.validation) setData(current => ({ ...current, validation: failure.response.data.validation })); } finally { setBusy(false); } };
  const exportData = () => { const payload = { format: "fixed-schedule-backup", version: 1, exported_at: new Date().toISOString(), assignments: data.template.assignments || [] }; const url = URL.createObjectURL(new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = `fixed-schedule-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url); setMessage("קובץ הגיבוי יוצא בהצלחה"); };
  const importData = async file => { try { const payload = JSON.parse(await file.text()); if (payload.format !== "fixed-schedule-backup" || !Array.isArray(payload.assignments)) throw new Error("קובץ הגיבוי אינו תקין"); await act("import_assignments", { assignments: payload.assignments }); } catch (failure) { setMessage(failure.message || "ייבוא הנתונים נכשל"); } };
  const openReview = async () => { setBusy(true); setMessage(""); try { const response = await manageFixedSchedule({ action: "validate", expected_updated_date: data.template.updated_date }); setData(current => ({ ...current, validation: response.data })); setReview(true); } catch (failure) { setMessage(failure.response?.data?.error || failure.message); } finally { setBusy(false); } };
  const mergeSlot = result => setData(current => { const key = result.slot_key; const assignments = (current.template.assignments || []).filter(item => !(item.day_of_week === key.day_of_week && item.break_type === key.break_type && item.station_id === key.station_id)); if (result.assignment) assignments.push(result.assignment); return { ...current, template: { ...current.template, ...result.template, assignments } }; });
  useEffect(() => { const params = new URLSearchParams(window.location.search), station = params.get("station"), breakType = params.get("break"); if (!station || !breakType || !data) return; window.setTimeout(() => document.getElementById(`fixed-slot-${day}-${breakType}-${station}`)?.scrollIntoView({ behavior: "smooth", block: "center" }), 250); }, [data, day]);
  const dayBreaks = useMemo(() => (data?.breaks || []).filter(brk => brk.active_days?.includes(day)), [data?.breaks, day]);
  if (isLoading) return <div className="flex justify-center py-20"><Loader2 className="animate-spin" /></div>;
  if (!data) return <p role="alert" className="py-20 text-center text-destructive">{error?.message || "טעינת הלוח נכשלה"}</p>;
  return <div className="space-y-4 pb-5"><div className="flex flex-wrap items-start justify-between gap-3"><div>{!embedded && <h1 className="text-2xl font-bold">לוח קבוע</h1>}<p className="text-sm text-muted-foreground">תבנית שבועית חוזרת · גרסה {data.template.version} · {data.template.status === "published" ? "פורסם" : "שמור"}</p></div><Button onClick={openReview} disabled={busy}><Send />פרסם לוח קבוע</Button></div><FixedScheduleToolbar day={day} setDay={setDay} busy={busy} onAuto={() => act("auto_assign")} onClear={async () => { if (await confirmDialog({ title: "ניקוי כל הלוח הקבוע", description: "כל השיבוצים בכל ימי השבוע יימחקו מהלוח הקבוע. ניתן למלא אותם מחדש בשיבוץ אוטומטי או ידני.", confirmLabel: "נקה הכל" })) act("clear_all"); }} onImport={importData} onExport={exportData} />{message && <p role="status" className="rounded-lg border bg-card p-3 text-sm">{message}</p>}<DraftSummaryBar summary={data.template.pending_report_summary} reportId={data.template.pending_report_id} /><div className="space-y-3">{dayBreaks.map(brk => <FixedBreakSection key={brk.id} brk={brk} stations={data.stations} assignments={data.template.assignments || []} day={day} onOpen={setEditing} />)}</div>{editing && <FixedTeacherSheet context={editing} day={day} template={data.template} onClose={() => setEditing(null)} onSaved={result => { mergeSlot(result); setEditing(null); setMessage("השיבוץ נשמר"); }} />}{review && <FixedPublishDialog validation={data.validation} busy={busy} onClose={() => setReview(false)} onPublish={async reason => { await act("publish", { override_reason: reason }); setReview(false); }} />}</div>;
}