import React, { useCallback, useEffect, useState } from "react";
import { ArrowRight, History, Loader2, Sparkles } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { manageSpecialDay } from "@/functions/manageSpecialDay";
import SpecialDaySettings from "@/components/special-days/SpecialDaySettings";
import SpecialStructurePanel from "@/components/special-days/SpecialStructurePanel";
import SpecialDayMatrix from "@/components/special-days/SpecialDayMatrix";
import SpecialMobileGroups from "@/components/special-days/SpecialMobileGroups";
import SpecialTeacherDialog from "@/components/special-days/SpecialTeacherDialog";
import SpecialValidationPanel from "@/components/special-days/SpecialValidationPanel";
import SpecialExportButtons from "@/components/special-days/SpecialExportButtons";

export default function SpecialDayEditor() {
  const { id } = useParams(), [data, setData] = useState(null), [busy, setBusy] = useState(false), [cell, setCell] = useState(null), [message, setMessage] = useState("");
  const load = useCallback(async () => { const r = await manageSpecialDay({ action: "get", special_day_id: id }); setData(r.data); }, [id]); useEffect(() => { load(); }, [load]);
  const act = async (action, payload = {}, success = "השינוי נשמר בטיוטה") => { setBusy(true); setMessage(""); try { const r = await manageSpecialDay({ action, special_day_id: id, expected_updated_date: data.day.updated_date, ...payload }); if (r.data.day) setData({ ...data, ...r.data }); else await load(); setMessage(success); return r.data; } catch (e) { setMessage(e.response?.data?.error || e.message); } finally { setBusy(false); } };
  if (!data) return <div className="flex justify-center py-20"><Loader2 className="animate-spin" /></div>; const draft = data.day.status === "draft";
  return <div className="space-y-4 pb-8"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><Link to="/special-days" aria-label="חזרה"><ArrowRight /></Link><div><h1 className="text-2xl font-bold">{data.day.name}</h1><p className="text-sm text-muted-foreground">{data.day.date} · גרסה {data.day.version} · {draft ? "טיוטה" : "פורסם"}</p></div></div><SpecialExportButtons day={data.day} assignments={data.assignments} /></div>{message && <p role="status" className="rounded-lg border bg-card p-2 text-sm">{message}</p>}{draft && <><SpecialDaySettings day={data.day} busy={busy} onSave={form => act("save_day", { data: form })} /><SpecialStructurePanel slots={data.slots} positions={data.positions} teachers={data.teachers} busy={busy} act={act} /><div className="flex flex-wrap gap-2"><Button disabled={busy || !data.requirements.length} onClick={() => act("generate", {}, "נוצרה טיוטה חכמה")}><Sparkles />יצירת טיוטה חכמה</Button><Button variant="outline" onClick={() => act("save_template", { name: data.day.name }, "התבנית נשמרה")} disabled={busy}>שמירה כתבנית</Button>{data.revisions?.length > 1 && <select aria-label="שחזור גרסה" className="h-10 rounded-md border bg-background px-3 text-sm" defaultValue="" onChange={e => e.target.value && act("restore", { revision_id: e.target.value }, "הגרסה שוחזרה")}><option value="">שחזור גרסה</option>{data.revisions.slice(1).map(r => <option key={r.id} value={r.id}>גרסה {r.version} · {r.action}</option>)}</select>}</div></>}<SpecialDayMatrix slots={data.slots} positions={data.positions} requirements={data.requirements} assignments={data.assignments} onRequirement={(position_id, time_slot_id, required_count) => act("set_requirement", { position_id, time_slot_id, required_count })} onEdit={draft ? setCell : () => {}} /><SpecialMobileGroups slots={data.slots} positions={data.positions} requirements={data.requirements} assignments={data.assignments} onEdit={draft ? setCell : () => {}} />{draft && <SpecialValidationPanel validation={data.validation} busy={busy} onValidate={async () => { const r = await act("validate", {}, "הבדיקה הושלמה"); if (r) setData(d => ({ ...d, validation: r })); }} onPublish={reason => act("publish", { override_reason: reason }, "היום המיוחד פורסם")} />}{cell && <SpecialTeacherDialog dayId={id} cell={cell} busy={busy} onClose={() => setCell(null)} onAssign={async teacher_id => { await act("assign", { time_slot_id: cell.slot.id, position_id: cell.position.id, teacher_id }); setCell(null); }} onRemove={async assignment_id => { await act("unassign", { assignment_id }); setCell(null); }} />}</div>;
}